"""
Generate src/utils/instrumentGeo.js from the Klongprem KML.
One-shot dev tool. Re-run if the KML changes.

Reads:
  - ../TBM-3D-Real/kmz/Klongprem Project.kml   (GIS export, outside repo)
  - src/utils/alignmentGeo.js                  (for LINE + CH, to compute chainage)
Writes:
  - src/utils/instrumentGeo.js                 (committed static data)

Run from repo root (wt-instmap):  python tools/extract-instrument-geo.py
"""
import xml.etree.ElementTree as ET
import json, math, re, os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
KML = os.path.join(ROOT, "..", "TBM-3D-Real", "kmz", "Klongprem Project.kml")
ALIGN = os.path.join(ROOT, "src", "utils", "alignmentGeo.js")
OUT = os.path.join(ROOT, "src", "utils", "instrumentGeo.js")
NS = "{http://www.opengis.net/kml/2.2}"

# --- parse LINE + CH out of alignmentGeo.js (keep chainage in sync) ---
def js_array(name, text):
    m = re.search(r"export const %s = (\[.*?\]);" % name, text, re.S)
    arr = m.group(1)
    arr = re.sub(r",(\s*\])", r"\1", arr)   # strip trailing commas -> valid JSON
    return json.loads(arr)

with open(ALIGN, encoding="utf-8") as f:
    atext = f.read()
LINE = js_array("LINE", atext)
CH = js_array("CH", atext)

def m_dist(a, b):
    R = 6371000.0
    la1, la2 = math.radians(a[1]), math.radians(b[1])
    x = math.radians(b[0] - a[0]) * math.cos((la1 + la2) / 2)
    y = la2 - la1
    return R * math.hypot(x, y)

def chainage_of(lng, lat):
    best = (1e9, 0.0)
    for i in range(len(LINE) - 1):
        a, b = LINE[i], LINE[i + 1]
        bx = m_dist(a, [b[0], a[1]]) * (1 if b[0] > a[0] else -1)
        by = m_dist(a, [a[0], b[1]]) * (1 if b[1] > a[1] else -1)
        px = m_dist(a, [lng, a[1]]) * (1 if lng > a[0] else -1)
        py = m_dist(a, [a[0], lat]) * (1 if lat > a[1] else -1)
        L2 = bx * bx + by * by
        t = 0 if L2 == 0 else max(0.0, min(1.0, (px * bx + py * by) / L2))
        cx, cy = t * bx, t * by
        d = math.hypot(px - cx, py - cy)
        if d < best[0]:
            best = (d, CH[i] + t * (CH[i + 1] - CH[i]))
    return best[1]

tree = ET.parse(KML)
doc = tree.getroot().find(f"{NS}Document")

def find_folder(name):
    for c in doc.iter(f"{NS}Folder"):
        nm = c.find(f"{NS}name")
        if nm is not None and nm.text == name:
            return c
    return None

# --- instruments: Ext/Inc/VW points -> cluster into sections (<25 m) ---
pf = find_folder("Point Features")
raw = []
for p in pf.findall(f".//{NS}Placemark"):
    nm = p.find(f"{NS}name"); name = nm.text if nm is not None else ""
    de = p.find(f"{NS}description"); desc = (de.text or "") if de is not None else ""
    ce = p.find(f".//{NS}Point/{NS}coordinates")
    if ce is None or not name:
        continue
    t = None
    for k, lbl in (("Extensometer", "EXT"), ("Inclinometer", "INC"), ("VW Piezometer", "VW")):
        if name.startswith(k):
            t = lbl
    if not t:
        continue
    lng, lat = map(float, ce.text.strip().split(",")[:2])
    raw.append((t, lng, lat, "Above Tunnel" in desc))

secs = []
for t, lng, lat, ab in raw:
    hit = None
    for s in secs:
        if m_dist((lng, lat), (s["lng"], s["lat"])) < 25:
            hit = s; break
    if hit is None:
        hit = {"lng": lng, "lat": lat, "types": set(), "ab": False, "n": 0}
        secs.append(hit)
    hit["types"].add(t); hit["ab"] = hit["ab"] or ab
    hit["lng"] = (hit["lng"] * hit["n"] + lng) / (hit["n"] + 1)
    hit["lat"] = (hit["lat"] * hit["n"] + lat) / (hit["n"] + 1)
    hit["n"] += 1

# sort by chainage descending (drill direction: high -> low), id IM-01..
secs_out = []
order = sorted(secs, key=lambda s: -chainage_of(s["lng"], s["lat"]))
TYPE_ORDER = {"EXT": 0, "INC": 1, "VW": 2}
for i, s in enumerate(order, 1):
    secs_out.append({
        "id": f"IM-{i:02d}",
        "lng": round(s["lng"], 7),
        "lat": round(s["lat"], 7),
        "chainage": round(chainage_of(s["lng"], s["lat"]), 1),
        "types": sorted(s["types"], key=lambda t: TYPE_ORDER[t]),
        "aboveTunnel": bool(s["ab"]),
    })

# --- settlement crosses: 'Instrument Tunnel' 2-point linestrings ---
crosses = []
for pm in doc.iter(f"{NS}Placemark"):
    de = pm.find(f"{NS}description")
    if de is None or (de.text or "").strip() != "Instrument Tunnel":
        continue
    ls = pm.find(f".//{NS}LineString/{NS}coordinates")
    if ls is None:
        continue
    pts = [list(map(float, c.split(",")[:2])) for c in ls.text.strip().split()]
    if len(pts) < 2:
        continue
    a, b = pts[0], pts[-1]
    crosses.append([[round(a[0], 7), round(a[1], 7)], [round(b[0], 7), round(b[1], 7)]])

# --- emit JS ---
def js(o):
    return json.dumps(o, ensure_ascii=False, separators=(",", ":"))

lines = []
lines.append("// GENERATED by tools/extract-instrument-geo.py — do not edit by hand")
lines.append("// Instrument monitoring sections + settlement crosses (real lat/lng from Klongprem KML)")
lines.append("// pure data + math — no maplibre/three import (jest-safe)")
lines.append("")
lines.append("export const INSTRUMENT_META = {")
lines.append('  EXT: { label: "Extensometer", shape: "square" },')
lines.append('  INC: { label: "Inclinometer", shape: "circle" },')
lines.append('  VW:  { label: "VW Piezometer", shape: "triangle" },')
lines.append("};")
lines.append("")
lines.append("export const INSTRUMENT_SECTIONS = [")
for s in secs_out:
    lines.append("  " + js(s) + ",")
lines.append("];")
lines.append("")
lines.append("// each entry = one drawn stroke [[lng,lat],[lng,lat]] (2 strokes make a '+')")
lines.append("export const SETTLEMENT_CROSSES = [")
for c in crosses:
    lines.append("  " + js(c) + ",")
lines.append("];")
lines.append("")
lines.append("// MapLibre GeoJSON source: one MultiLineString feature holding all strokes")
lines.append("export function settlementGeoJSON() {")
lines.append("  return {")
lines.append('    type: "FeatureCollection",')
lines.append('    features: [{ type: "Feature", properties: {}, geometry: { type: "MultiLineString", coordinates: SETTLEMENT_CROSSES } }],')
lines.append("  };")
lines.append("}")
lines.append("")

with open(OUT, "w", encoding="utf-8") as f:
    f.write("\n".join(lines))

print(f"sections={len(secs_out)} crosses={len(crosses)} -> {OUT}")
